services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped

    networks:
      - db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./data:/data
      - ./src/ex02/table.sh:/usr/local/bin/table.sh
      - ./src/ex03/automatic_table.sh:/usr/local/bin/automatic_table.sh
      - ./src/ex04/items_table.sh:/usr/local/bin/items_table.sh

    secrets:
      - postgres_password

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s


  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"
    networks:
      - db
      - gui

    environment:
      ADMINER_DEFAULT_SERVER: postgres


networks:
  db:
    driver: bridge
    internal: true
  gui:
    driver: bridge


secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
